package manejo_errores

import "fmt"

// La funci√≥n panic nos permite entrar en p√°nico = detener ejecuci√≥n
// La funci√≥n recover nos permite recuperarnos de un panic

func Division(dividen, divisor int) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("Me recuper√© del p√°nico")
		}
	}()

	validateZero(divisor)
	fmt.Println(dividen / divisor)
}

func validateZero(divisor int) {
	if divisor == 0 {
		panic("ü§ï no puedes dividir por cero")
	}
}
